[placeholders]
project_version = { type = "string", prompt = "Project version", default = "0.1.0", regex = "^\\d+\\.\\d+(\\.\\d+)?$" }
cpp_standard = { type = "string", prompt = "C++ standard", default = "c++20", choices = ["c++11", "c++14", "c++17", "c++20", "c++23"] }