name: 运行测试

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test_windows:
    strategy:
      matrix:
        presets:
          [
            msvc-x64-md-dbg,
            msvc-x86-md-dbg,
            msvc-x64-mt-dbg,
            msvc-x86-mt-dbg,
          ]
    runs-on: windows-latest
    steps:
      # 拉取仓库
      - uses: actions/checkout@v4
      # 配置MSVC环境
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      # 编译运行测试
      - name: Build and Test
        run: |
          cmake --preset ${{ matrix.presets  }}
          cmake --build build/${{ matrix.presets  }}
          cd build/${{ matrix.presets  }}
          ctest -C Debug -VV
